const fs = require('fs');
const https = require('https');
const urls = [
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/1.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/2.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/3.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/4.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/5.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/6.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/7.json',
  'https://raw.githubusercontent.com/Lawrie3607/booklet_library_backup_2025-12-31/refs/heads/main/8.json'
];

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      if (res.statusCode >= 400) return reject(new Error('HTTP ' + res.statusCode + ' ' + url));
      let data = '';
      res.setEncoding('utf8');
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => resolve(data));
    }).on('error', reject);
  });
}

(async function(){
  try {
    const parts = [];
    for (const u of urls) {
      console.log('Fetching', u);
      const t = await fetchText(u);
      parts.push(t);
    }
    const merged = parts.join('');
    const safe = merged.replace(/`/g, '\\`');
    const outPath = './services/defaultLibrary.ts';
    const content = `/** Auto-generated by scripts/merge_booklets.cjs */\n\nexport const DEFAULT_LIBRARY_JSON = ` + '`' + safe + '`' + `;\n`;
    fs.writeFileSync(outPath, content, 'utf8');
    console.log('Wrote', outPath);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
